
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_DETAILS_REQUEST ='GET_PRODUCT_DETAILS_REQUEST'; 
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';
export const GET_PRODUCT_DETAILS_RESET ='GET_PRODUCT_DETAILS_RESET'; 

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const DFETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const DFETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const DFETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
